services:
  nginx:
    image: nginx:alpine
    container_name: doctor_symfony_nginx
    volumes:
      - /var/www/html:/var/www/html
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  php-fpm:
    build: docker/prod/php-fpm
    container_name: doctor_symfony_php
    working_dir: /var/www/html
    volumes:
      - /var/www/html:/var/www/html
    environment:
      SYMFONY_ENV: prod
    depends_on:
      - db
  db:
    image: mariadb:11.5
    container_name: doctor_symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:

