services:
  nginx:
    image: nginx:alpine
    container_name: doctor_symfony_nginx
    volumes:
      - /var/www/html:/var/www/html
      - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/local/php-fpm
    container_name: doctor_symfony_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html #volumes for local development
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: doctor_symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306" # required for local connection
    volumes:
      - db_data:/var/lib/mysql
    mem_limit: 1g
    cpu_shares: 512

volumes:
  db_data: