services:
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - /var/www/html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  php-fpm:
    build: ./php-fpm
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - /var/www/html/symfony:/var/www/html
    environment:
      SYMFONY_ENV: prod
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data:

